---

dist: "focal"  # sqlite3 v3.31.1
language: "python"
python: "3.6"
before_install: "pip install poetry codecov"
install: "poetry install --verbose"
script:
  - "pytest --verbose --cov=csvblend tests"
  - "prospector csvblend"
  - "black --check csvblend"
  - "isort --recursive --check-only csvblend"
  - "codecov"
